### PR TITLE
Remove Makefile and code cleanup

### PR DESCRIPTION
**Pull request by leesei**
Changes to be committed:
	modified:   .gitignore
	deleted:    Makefile
	modified:   bin/rfc
	modified:   index.js
	new file:   jsdoc.conf.json
	modified:   package.json
	deleted:    rfc.1

### CODE REVIEW

**Comment by leesei** [comment]
This closes #7

**Comment by leesei** [comment]
use `path.resolve()` instead of string concat
update jsdocs
use strict equality if possible
remove unused variables
use npm scripts instead of Makefile

**Comment by jwerle** [comment]
@leesei Thanks! I've merged, released, and published the changes. I'll add you as a collaborator to this project

**Comment by leesei** [comment]
Thanks

**Pull request merged**
